# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: brew install leiningen
    init: lein deps
    command: bin/kaocha --watch

vscode:
  extensions:
    - betterthantomorrow.calva